### ISSUE TITLE
D2R character file won't load properly after moving from D2

### ISSUE THREAD

**Issue by Gullara** [pairofdocs/gomule-d2r#9]
I transferred several character into D2R from D2 and proceeded to then open them up with GoMule. All but one character works. When I open him up I get a window with an empty inventory/stash and the window's title is "Disconnected". 

![image](https://user-images.githubusercontent.com/6046326/134782723-3fd585ca-fd22-46b0-9334-c26be5924134.png)

I am using version 0.21 of GoMule.

I've attached the d2s file of the character for diagnosis. To let github upload it I changed the file format; simply rename it back to "Gulmyr.d2s" to use it. Let me know if any other information is needed. 

[Gulmyr.csv](https://github.com/pairofdocs/gomule-d2r/files/7230216/Gulmyr.csv)

Thank you.

**Comment by pairofdocs** [comment]
I'll take a look, thanks for the details and file.

**Comment by pairofdocs** [comment]
I think I found the issue. It was the iron golem item in the save file.

The newest release has this fixed

**Comment by Gullara** [comment]
I can confirm that the fix works. Thanks!

**Comment by pairofdocs** [comment]
Right on!
